### ISSUE TITLE
Picking the correct Naming series

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#1]
Hi, 

Tried to set the correct naming series for when the user creates documents and returns.

Purchase receipt normal: PRC.#######
Purchase return: PNH.#######

Purchase Invoice: PIH.#######
Purchase Credit Note: PCR.######

Delivery Note: SDH.#######
Return: SRH.#######

Sales Invoice: SIH.########
Sales Credit: SCR.########

I tried with custom script using what i found on forums, but does not work.

Please assist.

Kind regards
Hemant

**Comment by agritheory** [comment]
@hpema I will set these up locally and export them so you can import them into the development and production instances.

**Comment by agritheory** [comment]
@hpema 
I have updated these in aptronics.agritheory.com but this prompted additional thoughts:
1) There's no date involved. I think a short year number should be used.
2) I think you want series for Sales Order and Purchase Order too.
3) Forcing the correct series can be done with a custom script, though we'll want to sync with the final versions of the naming series.

**Comment by hpema** [comment]
@agritheory 

 
> 1. There's no date involved. I think a short year number should be used.
I agree, but for now want to just replace current x3 system, will the size of the number impact the performance?

> 2. I think you want series for Sales Order and Purchase Order too.
I agree -  will add the series tomorrow to the instance for all the doctypes

> 3. Forcing the correct series can be done with a custom script, though we'll want to sync with the final versions of the naming series.
will update tomorrow morning...

**Comment by hpema** [comment]
All series have been updated where there is a selection needed on returns - need to make series readonly.

Let me know once its been updated so I can test.

thnx

**Comment by agritheory** [comment]
- [x] Make script to select correct series name/ return series name
- [x] Make naming series field read only once script is working
