### ISSUE TITLE
Stock Balance by batch and age

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#13]
Hi,

The stock report should show stock by lot with its respective age as well. Currently showing averages, but I think if broken by batch we can show the actuals sorted by oldest firsts.

Also, zero balance items should not show.

kind regards
Hemant

**Comment by agritheory** [comment]
@hpema Which stock report?

**Comment by hpema** [comment]
Stock Balances report, and there is an age data show check box, but the report does not generate any data.

Thanks

**Comment by SaiFi0102** [comment]
Was this resolved?
