### ISSUE TITLE
Customers should have parent

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#16]
Hi Team,

We need to be able to link customers to parent customers - or group customer.

Currently we have many EOH companies and we are creating customer accounts for each that we deal with, but for reporting or aging we would like to see all those customers in one list, so maybe the aging report should sort by group company and the children after. Not sure how we would handle the group customer itself.... Unless we just create a text field that will hold and acronum or something. Its how we doing some customers in X3 but not as effective as we would like it to be.

Lets discuss

kind regards
Hemant

**Comment by agritheory** [comment]
@hpema Can Customer Group be leveraged for this? Customers are not currently accessible in a tree structure.

**Comment by hpema** [comment]
Hi Tyler, based on our discussion we will attempt customer group as an option, and im sure that will work.
