### ISSUE TITLE
Create Multiple PO from Sales Order

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#19]
Hi Team,

We would like to generate draft POs from Sales order line suppliers setup.

Once the sales order lines have got the supplier we planning to buy from and updated, when "Create"-Purchase order is selected, we would like to get all the POs generated at once - or by clicking a button on the popup form.

We have tested that if you selected all the items, and 1 of the suppliers then the po generated is only for that item set for the supplier. If we can get all generated as draft that would be ideal.

will discuss further - can use SAL-ORD-2019-00015 for testing on aptronics.agritheory.com

**Comment by SaiFi0102** [comment]
Leave the Supplier field in the "Create Purchase Order" dialog and select all items to make multiple POs. If there are multiple suppliers, it will make multiple POs
![Multiple POs](https://user-images.githubusercontent.com/328330/68900071-e17e0080-0754-11ea-9f2d-1f938765f8ad.gif)

**Comment by hpema** [comment]
Hi Saif,

Tried that but got this error. We trying to duplicate and order from x3 from decemeber last year so not sure if that has anything to do with it...

![image](https://user-images.githubusercontent.com/5782668/68920724-c7f1ae80-077e-11ea-8664-7fc5a3039760.png)

when testing on todays order date and delivery date in the future then it works

**Comment by SaiFi0102** [comment]
I understand the problem and I'll take care of it
Notes:
1. Delivery Date on Sales Order Item should be editable after submission
2. If Delivery Date is in the past then PO's Reqd By Date should be today (by default) to prevent this error

**Comment by SaiFi0102** [comment]
@agritheory Updated erpnext branch and aptronics app

**Comment by hpema** [comment]
when creating multiple or single POs from Sales order the taxes dont load correclly

Tax template gets loaded but does not load taxes in table

![image](https://user-images.githubusercontent.com/5782668/69265020-1fee4200-0bd1-11ea-93d7-37f3891daa85.png)

**Comment by hpema** [comment]
Tested, and working...thnks
