### ISSUE TITLE
Group same items on print format in delivery issue on print

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#2]
Hi teyam,

When clicking on "Group same items" it does not show the combined serial numbers on the combined row. Only first rows serials show, not all the rows that get combined.

Checked on MAT-DN-2019-00021

kind regards
Hemant

**Comment by agritheory** [comment]
@hpema Saif has a fix he'll be pulling into the Aptronics features branch

**Comment by SaiFi0102** [comment]
I've included this in the aptronics branch.
