### ISSUE TITLE
Sales Invoice wharehouse resets

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#20]
Hi Team,

When making any changes after creating an invoice from shipment changes the wharehouse on lines back to the default wharehouse and not the goods-in-transit wharehouse. User has to change it back as it complains about stock levels - this is how we found it reset to default wharehouse.

**Comment by hpema** [comment]
Seems like if there is a config issue and mandotary fields are missing then wharehouse is getting reset. In my case it was the item group missing sales and cost accounts. Setting this in itemgroup fixed the issue.

**Comment by hpema** [comment]
Please add warning to sales invoice if wharehouse link to stock/delivery not goods in transit wharehouse.

**Comment by agritheory** [comment]
Feature added in 79aa738d7da60a15b08be7d785cbd800cfd8002d
