### ISSUE TITLE
Over Delivery/Receipt Allowance (%)

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#21]
Hi Team,

We should come up with a better way to manage the setting for our customisation.

![image](https://user-images.githubusercontent.com/5782668/68779069-b607f280-063c-11ea-8d73-92080d29545f.png)

**Comment by SaiFi0102** [comment]
@agritheory @hpema 
Solved with https://github.com/SaiFi0102/erpnext/commit/95e78ce5ced077c3b3f7622ac74de2ba1e927fb9

**Comment by SaiFi0102** [comment]
@hpema did you review this?

**Comment by hpema** [comment]
Setting the "Over Delivery/Receipt Allowance (%)" value to 0% now allows us to post delivery note. Thanks.
