### ISSUE TITLE
Security on Sales orders overwritten

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#28]
Hi Team,

When I do a bench update then the permissions I add on the sales order for Purchase users is removed.

**Comment by agritheory** [comment]
These are the permissions being applied by the application: 
https://github.com/Aptronics/aptronics/blob/master/aptronics/aptronics/custom/sales_order.json#L316
You are currently exporting permissions to the application which resets them at the time of migrate.
1. Keep these up to date by exporting customizations when you change permissions (on all relevant doctypes)
2. Manage permissions only in the database and do not export permissions at all

**Comment by hpema** [comment]
I will export permissions so that they live in the app and will be used is the different instances we using: Dev, Training and liveprep
