### ISSUE TITLE
Issues found during demo

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#3]
Hi Team,

Few issues when doing demo

1) When generating sales order, its great that we can now submit the sales order and update the Supplier on the lines after its submitted. This is great as it works with our workflow. This allows us to seperate the role. But... When generating the purchase order from sales order the selection screen does not match the supplier with the items... I think the selection screen is somewhat redunant cause if we already select the supplier on the line, it should just know which lines to group and add to a PO.

2) When going from material request - the if the Sales order is USD and we generate the material request, the purchase order is come out as USD too, when it should be the currency of the selected supplier - which in our test case was ZAR.

3) Flow needs to change or added when doing customer invoice. We have situations where we do multiple shipments and this needs to be added customer invoice and we would do this from invoice screen. Doing it from shipment screen is what we built now, but can we relook at adding from invoice screen as well?

**Comment by agritheory** [comment]
1) To recap:
Set supplier here. 
![image](https://user-images.githubusercontent.com/18033666/66394480-3fc00280-e9a3-11e9-8333-59aa97af1cf7.png)

Click on create Purchase Order here:
![image](https://user-images.githubusercontent.com/18033666/66394505-4babc480-e9a3-11e9-8c3f-b5efbed6d954.png)

THIS is the dialog you now want to bypass and directly create draft Purchase Order(s) for each unique supplier mentioned?

![image](https://user-images.githubusercontent.com/18033666/66394516-56fef000-e9a3-11e9-9822-419b3999c2a6.png)

**Comment by agritheory** [comment]
2) Suppliers that have non-native (or non-default, whichever way of thinking about it is more helpful) should have A) a payable account in said currency (at least one payable account per currency you do business in) and 2) it should be set in the Supplier payable accounts. IMPORTANT: At this time Suppliers cannot have more than one currency. 

A: 
![image](https://user-images.githubusercontent.com/18033666/66394926-456a1800-e9a4-11e9-914a-ca458658008d.png)

B:
![image](https://user-images.githubusercontent.com/18033666/66394862-28354980-e9a4-11e9-860c-b7fd89dc2b20.png)

**Comment by agritheory** [comment]
3) There's a builtin way to do this, let's test if it is satisfactory:

A) Select "Get Items From" ... "Delivery Note":
![image](https://user-images.githubusercontent.com/18033666/66395114-a265ce00-e9a4-11e9-94a6-dd92c5c32b9f.png)

B) Select Delivery Notes from the dialog (there are none shown in this screen shot). 
![image](https://user-images.githubusercontent.com/18033666/66395148-bad5e880-e9a4-11e9-81bc-c6ecc11f9424.png)

**Comment by agritheory** [comment]
@hpema We have (thankfully) an unlimited number of issues provided by GitHub, we can split this into three issues next time so we could have a discrete dialog about each, if required.

**Comment by hpema** [comment]
> 1. There's a builtin way to do this, let's test if it is satisfactory:
> 
> A) Select "Get Items From" ... "Delivery Note":
> ![image](https://user-images.githubusercontent.com/18033666/66395114-a265ce00-e9a4-11e9-94a6-dd92c5c32b9f.png)
> 
> B) Select Delivery Notes from the dialog (there are none shown in this screen shot).
> ![image](https://user-images.githubusercontent.com/18033666/66395148-bad5e880-e9a4-11e9-81bc-c6ecc11f9424.png)

I followed this option but the flags and store was not set according to what it needs to be when doing from delivery note. So had to set manually the "stock" flag and stores.

**Comment by agritheory** [comment]
> So had to set manually the "stock" flag and stores.

We can find a way to automate that better, for sure. 

- [x]  Make Sales Invoice multiple Delivery Note dialog populate "update stock" and "warehouse" from Delivery Note.

**Comment by agritheory** [comment]
Added 15/10/19
