### ISSUE TITLE
Customer Returns journals not same as delivery

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#32]
Hi team,

We noticed that when doing a return the wharehouse is not "Good delivered not invoiced" account, its crediting the cost of sales account.

Can we get this to be the "Goods delivered not invoiced" wharehouse?

Thanks

**Comment by agritheory** [comment]
Yes I think so. I will look into this and resolve it.

**Comment by agritheory** [comment]
@hpema Please confirm this has been resolved

**Comment by hpema** [comment]
This is resolved if I follow the workflow of doing the return on invoice first and then doing the delivery return. We will document this for the users to follow.
