### ISSUE TITLE
Selecting from doctypes

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#4]
When selecting from previous doctypes the list should be restricted to only the current customer or supplier if it relates to invoices picking from previous stock docs.

So if Im on an supplier invoice I should not be able to select any po or receipt that does not belong to the currently selected supplier or allowed to choose blank on the pick list to allow all docytpes to load. Have to select a supplier, incase we select the "Get from" before selecting the supplier.

Same should apply to the sales documents

**Comment by agritheory** [comment]
- [x] Sales Invoice select DN only from customer's Sales Order (in dialog)
- [x] Delivery Note select only from customer's Sales Orders (in dialog)

PO/ PR/ PI leave alone for now

**Comment by agritheory** [comment]
@hpema Marking this one resolved. Will demo on next call.
