### ISSUE TITLE
Po to display customer

### ISSUE THREAD

**Issue by hpema** [Aptronics/aptronics#5]
Display customer name on Purchase doctypes if linked on Sales Order

**Comment by SaiFi0102** [comment]
- [x] Add Customer Field in PO
Should it also be in PREC and PINV? You can have multiple purchase order in Purchase Receipt and Purchase Invoice therefore multiple customer.

**Comment by hpema** [comment]
Yes, it should be on all supplier docs if linked to sales order. We will not be linking multiple POs from different customer that could end up on Supplier invoices. The process will be to link only 1 per customer even though there could be multiple supplier invoices for that sales order, they will not be crossed linked.

Cases where we have stock orders wont be linked to Sales orders so wont show customer info.

**Comment by agritheory** [comment]
WIP as of 18/10/19 @SaiFi0102, review requested on [fork](https://github.com/agritheory/aptronics/commit/981e97bf1e20c1aedaac66e2f0551732e3333684)

**Comment by hpema** [comment]
The fork seems to be for buyer info - are we still working on customer info to show on PO/PRecpt/PINV when linked to a sales order?

**Comment by agritheory** [comment]
Solved with 2f250ca11a8786a646e9afb566728b1ce44133be
